---
- name: This is a hello-world example
  hosts: linux_hosts
  #connection: local
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile.txt
